### GET /todos
GET http://localhost:8081/todos
Content-Type: application/json

### GET /todos/:id
GET http://localhost:8081/todos/6465e7ba56aa5ef0d3e61813
Content-Type: application/json

### POST /todos - { "task": "Make a wish" }
POST http://localhost:8081/todos
Content-Type: application/json

{
    "task": "Make a wish",
    "checked": true
}

### POST /todos - { "stuff": "" }
POST http://localhost:8081/todos
Content-Type: application/json

{
    "stuff":""
}

### PATCH /todos/:id - { "checked": true }
PATCH http://localhost:8081/todos/6465e9f124621b84991e7f76
Content-Type: application/json

{
 "checked": false
}

### PATCH /todos/:id - { "checked": "" }
PATCH http://localhost:8081/todos/2
Content-Type: application/json

{
 "checked": ""
}

### DELETE /todos
DELETE http://localhost:8081/todos

### DELETE /todos/:id
DELETE http://localhost:8081/todos/6465e7ba56aa5ef0d3e61813